atleisure:
  username: <%= ENV["ATLEISURE_USERNAME"] %>
  password: <%= ENV["ATLEISURE_PASSWORD"] %>
  test_mode: <%= ENV["ATLEISURE_TEST_MODE"] %>

kigo:
  subscription_key: <%= ENV["KIGO_SUBSCRIPTION_KEY"] %>

kigolegacy:
  username: <%= ENV["KIGO_LEGACY_USERNAME"] %>
  password: <%= ENV["KIGO_LEGACY_PASSWORD"] %>

jtb:
  id:       <%= ENV["JTB_ID"] %>
  user:     <%= ENV["JTB_USER"] %>
  password: <%= ENV["JTB_PASSWORD"] %>
  company:  <%= ENV["JTB_COMPANY"] %>
  url:      <%= ENV["JTB_URL"] %>

sqs:
  region:            <%= ENV["CONCIERGE_SQS_REGION"] %>
  queue_name:        <%= ENV["CONCIERGE_SQS_QUEUE_NAME"] %>
  access_key_id:     <%= ENV["CONCIERGE_SQS_KEY_ID"] %>
  secret_access_key: <%= ENV["CONCIERGE_SQS_SECRET_ACCESS_KEY"] %>

waytostay:
  url:           <%= ENV["WAYTOSTAY_URL"] %>
  token_url:     <%= ENV["WAYTOSTAY_TOKEN_URL"] %>
  client_id:     <%= ENV["WAYTOSTAY_CLIENT_ID"] %>
  client_secret: <%= ENV["WAYTOSTAY_CLIENT_SECRET"] %>

ciirus:
  url:      <%= ENV["CIIRUS_URL"] %>
  username: <%= ENV["CIIRUS_USERNAME"] %>
  password: <%= ENV["CIIRUS_PASSWORD"] %>

saw:
  username:    <%= ENV["SAW_USERNAME"] %>
  password:    <%= ENV["SAW_PASSWORD"] %>
  url:         <%= ENV["SAW_URL"] %>
  url_rewrite: false

woori:
  url:                    <%= ENV["WOORI_URL"] %>
  api_key:                <%= ENV["WOORI_API_KEY"] %>
  import_files_type:      <%= ENV["WOORI_IMPORT_FILES_TYPE"] %>
  properties_import_file: <%= ENV["WOORI_PROPERTIES_IMPORT_FILE"] %>
  units_1_import_file:    <%= ENV["WOORI_UNITS_1_IMPORT_FILE"] %>
  units_2_import_file:    <%= ENV["WOORI_UNITS_2_IMPORT_FILE"] %>
  units_3_import_file:    <%= ENV["WOORI_UNITS_3_IMPORT_FILE"] %>

woori:
  url:              <%= ENV["WOORI_URL"] %>
  api_key:          <%= ENV["WOORI_API_KEY"] %>
  import_files_dir: <%= ENV["WOORI_IMPORT_FILES_DIR"] %>
