atleisure:
  username: <%= ENV["ATLEISURE_USERNAME"] %>
  password: <%= ENV["ATLEISURE_PASSWORD"] %>
  test_mode: "No"


kigo:
  subscription_key: <%= ENV["KIGO_SUBSCRIPTION_KEY"] %>

kigolegacy:
  username: <%= ENV["KIGO_LEGACY_USERNAME"] %>
  password: <%= ENV["KIGO_LEGACY_PASSWORD"] %>

jtb:
  id:       <%= ENV["JTB_ID"] %>
  user:     <%= ENV["JTB_USER"] %>
  password: <%= ENV["JTB_PASSWORD"] %>
  company:  <%= ENV["JTB_COMPANY"] %>
  url:      <%= ENV["JTB_URL"] %>

sqs:
  region:            <%= ENV["CONCIERGE_SQS_REGION"] %>
  queue_name:        <%= ENV["CONCIERGE_SQS_QUEUE_NAME"] %>
  access_key_id:     <%= ENV["CONCIERGE_SQS_KEY_ID"] %>
  secret_access_key: <%= ENV["CONCIERGE_SQS_SECRET_ACCESS_KEY"] %>
