atleisure:
  username: <%= ENV["ATLEISURE_USERNAME"] %>
  password: <%= ENV["ATLEISURE_PASSWORD"] %>
  test_mode: "<%= ENV['ATLEISURE_TEST_MODE'] %>"

kigo:
  subscription_key: <%= ENV["KIGO_SUBSCRIPTION_KEY"] %>

kigolegacy:
  username: <%= ENV["KIGO_LEGACY_USERNAME"] %>
  password: <%= ENV["KIGO_LEGACY_PASSWORD"] %>

jtb:
  api:
    id:       <%= ENV["JTB_API_ID"] %>
    user:     <%= ENV["JTB_API_USER"] %>
    password: <%= ENV["JTB_API_PASSWORD"] %>
    company:  <%= ENV["JTB_API_COMPANY"] %>
    url:      <%= ENV["JTB_API_URL"] %>
    test:     true
  sftp:
    user_id:  <%= ENV["JTB_SFTP_USER_ID"] %>
    password: <%= ENV["JTB_SFTP_PASSWORD"] %>
    port:     <%= ENV["JTB_SFTP_PORT"] %>
    host:     <%= ENV["JTB_SFTP_HOST"] %>
    tmp_path: <%= ENV["JTB_SFTP_TMP_PATH"] %>

sqs:
  region:            <%= ENV["CONCIERGE_SQS_REGION"] %>
  queue_name:        <%= ENV["CONCIERGE_SQS_QUEUE_NAME"] %>
  access_key_id:     <%= ENV["CONCIERGE_SQS_KEY_ID"] %>
  secret_access_key: <%= ENV["CONCIERGE_SQS_SECRET_ACCESS_KEY"] %>

waytostay:
  url:           <%= ENV["WAYTOSTAY_URL"] %>
  token_url:     <%= ENV["WAYTOSTAY_TOKEN_URL"] %>
  client_id:     <%= ENV["WAYTOSTAY_CLIENT_ID"] %>
  client_secret: <%= ENV["WAYTOSTAY_CLIENT_SECRET"] %>

ciirus:
  url:      <%= ENV["CIIRUS_URL"] %>
  username: <%= ENV["CIIRUS_USERNAME"] %>
  password: <%= ENV["CIIRUS_PASSWORD"] %>

saw:
  username:    <%= ENV["SAW_USERNAME"] %>
  password:    <%= ENV["SAW_PASSWORD"] %>
  url:         <%= ENV["SAW_URL"] %>
  url_rewrite: true

poplidays:
  url:        <%= ENV["POPLIDAYS_URL"] %>
  client_key: <%= ENV["POPLIDAYS_CLIENT_KEY"] %>
  passphrase: <%= ENV["POPLIDAYS_PASSPHRASE"] %>

rentalsunited:
  username: <%= ENV["RENTALS_UNITED_USERNAME"] %>
  password: <%= ENV["RENTALS_UNITED_PASSWORD"] %>
  url:      <%= ENV["RENTALS_UNITED_URL"] %>
