supplier:
  username: "roomorama"
  password: "p4ssw0rd"
  token: <%= ENV["_TEST_PARTNER_TOKEN"] %>

jtb:
  id: "123"
  user: "roomorama-test"
  password: "roomorama-pwd"
  company: "Roomorama"
  url: "http://www.example.org"

atleisure:
  username: "test-username"
  password: "test-password"

kigo:
  subscription_key: "123-key"

kigolegacy:
  username: "roomorama-user"
  password: "roomorama-pass"

waytostay:
  url: "https://apis.sandbox.waytostay.com:25443"
  token_url: "/oauth"
  client_id: a0210a941690c1927350
  client_secret: e151f3a21a59c7a336f6

