supplier:
  username:  "roomorama"
  password:  "p4ssw0rd"
  token:     <%= ENV["_TEST_PARTNER_TOKEN"] %>
  test_mode: false
  quoted_mode: "No"
  bool_mode: No

jtb:
  id:       "123"
  user:     "roomorama-test"
  password: "roomorama-pwd"
  company:  "Roomorama"
  url:      "http://www.example.org"

atleisure:
  username: "test-username"
  password: "test-password"
  test_mode: "No"

kigo:
  subscription_key: "123-key"

kigolegacy:
  username: "roomorama-user"
  password: "roomorama-pass"

sqs:
  region:            "us-east-1"
  queue_name:        "concierge-test"
  access_key_id:     "key-test"
  secret_access_key: "secret-test"

waytostay:
  url:           "https://test.api.com"
  token_url:     "/oauth"
  client_id:     test_id
  client_secret: test_secret

ciirus:
  url:      "http://www.example.org"
  username: "roomorama-user"
  password: "roomorama-pass"

saw:
  username:    "roomorama-user"
  password:    "roomorama-pass"
  url:         "http://www.example.org"
  url_rewrite: true

poplidays:
  url:        'www.example.org'
  client_key: "123"
  passphrase: "123"

rentalsunited:
  username: "roomorama-user"
  password: "roomorama-pass"
  url:      "http://www.example.org"

avantio:
  code_partner: "code_partner"
  username:     "username"
  password:     "password"