- ROOMORAMA_SECRET_JTB
- ROOMORAMA_SECRET_KIGO_LEGACY
- ROOMORAMA_SECRET_KIGO
- ROOMORAMA_SECRET_ATLEISURE
- ROOMORAMA_SECRET_POPLIDAYS
- ROOMORAMA_SECRET_WAYTOSTAY
- ROOMORAMA_SECRET_CIIRUS
- ROOMORAMA_SECRET_SAW
- ROOMORAMA_SECRET_WOORI
- WAYTOSTAY_URL
- WAYTOSTAY_TOKEN_URL
- WAYTOSTAY_CLIENT_ID
- WAYTOSTAY_CLIENT_SECRET
- CIIRUS_URL
- CIIRUS_USERNAME
- CIIRUS_PASSWORD
